namespace: debtsapp
appDomain: debtsapp.app.macsia.fun
storageClassName: local-path

imagePullSecretName: ghcr-pull

backend:
  name: debts-bot
  image:
    repository: ghcr.io/macsiaproduction/debtsapp-backend
    tag: sha-3722691
    pullPolicy: Always
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCpuUtilization: 15

frontend:
  name: debts-frontend
  image:
    repository: ghcr.io/macsiaproduction/debtsapp-frontend
    tag: sha-3722691
    pullPolicy: Always
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

postgres:
  image: postgres:15-alpine
  user: debtsbot
  database: debtsbot
  storageSize: 10Gi

neo4j:
  image: neo4j:5-community
  user: neo4j
  storageSize: 10Gi

monitoring:
  releaseName: monitoring
