spring.datasource.url=jdbc:postgresql://debts_bot_db:5432/debtsbot
spring.datasource.username=debtsbot
spring.datasource.password=debtsbot
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1

spring.liquibase.enabled=true
spring.data.jdbc.repositories.enabled=true

sessionToken.lifetime=1m
jwt.lifetime = 10m
spring.profiles.active=main