server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/debtsbot
spring.datasource.username=debtsbot
spring.datasource.password=debtsbot
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1

spring.liquibase.enabled=true

spring.data.jdbc.repositories.enabled=true

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=debtsbot123

bot.token=PASTE_YOUR_TOKEN
bot.name=DebtsAppBot
telegram.bot.enabled=false

sessionToken.lifetime=1m
jwt.lifetime=10m
linkToken.lifetime=5m
